"""REmoved task table

Revision ID: 97beb9cbe1b9
Revises: d08f89c4da06
Create Date: 2023-08-10 11:08:35.240013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97beb9cbe1b9'
down_revision = 'd08f89c4da06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('due_time', sa.TIME(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
