"""Initial migration

Revision ID: d08f89c4da06
Revises: 
Create Date: 2023-08-10 02:34:58.634160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08f89c4da06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint('uq_username', ['username'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_username', type_='unique')


    # ### end Alembic commands ###

# op.create_foreign_key("fk_name", "child_table", "parent_table", ["child_column"], ["parent_column"])

